service: vrc-vs-server

frameworkVersion: "3"

plugins:
  - serverless-python-requirements

custom:
  table: ${self:service}-${opt:stage}-table
  pythonRequirements:
    dockerizePip: true
    dockerImage: public.ecr.aws/sam/build-python3.10:latest
    useStaticCache: false
    useDownloadCache: false
    layer: true
  deploymentBucket:
    name: net.akakitune87.serverlessdeoloy

provider:
  name: aws
  runtime: python3.10
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "arn:aws:dynamodb:ap-northeast-1:*:*"
    - Effect: Allow
      Action:
        - s3:*
      Resource: "arn:aws:s3:::*"
  timeout: 7
  logRetentionInDays: 14
  tracing:
    apiGateway: true
    lambda: true

package:
  individually: true
  exclude:
    - node_modules/**
    - .gitignore
    - package-lock.json
    - requirements.txt
    - serverless.yml
    - .env
    - memo.txt
    - example.py
    - src/**
    - LICENSE

layers:
  utilsLayer:
    path: src/layers/utils
    name: ${opt:stage}-${self:service}-utilsLayer
    description: utils
    compatibleRuntimes:
      - python3.8

functions:
  rv_entry_regist:
    handler: src/lambda/rv_entry_regist/handler.main
    package:
      include:
        - src/lambda/rv_entry_regist/handler.py
    environment:
      TABLE: ${self:custom.table}
      NOTIC_URL: ${env:NOTIC_URL}
      OTHELLO_URL: ${env:OTHELLO_URL}
    layers:
      - { Ref: UtilsLayerLambdaLayer }
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: /rv/entry/regist
          method: get
  rv_matching_check:
    handler: src/lambda/rv_matching_check/handler.main
    package:
      include:
        - src/lambda/rv_matching_check/handler.py
    environment:
      TABLE: ${self:custom.table}
    layers:
      - { Ref: UtilsLayerLambdaLayer }
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: /rv/entry/check
          method: get
  rv_action_regist:
    handler: src/lambda/rv_action_regist/handler.main
    package:
      include:
        - src/lambda/rv_action_regist/handler.py
    environment:
      TABLE: ${self:custom.table}
    layers:
      - { Ref: UtilsLayerLambdaLayer }
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: /rv/action/regist
          method: get
  rv_action_check:
    handler: src/lambda/rv_action_check/handler.main
    package:
      include:
        - src/lambda/rv_action_check/handler.py
    environment:
      TABLE: ${self:custom.table}
    layers:
      - { Ref: UtilsLayerLambdaLayer }
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: /rv/action/check
          method: get
  rv_entry_canncel:
    handler: src/lambda/rv_entry_canncel/handler.main
    package:
      include:
        - src/lambda/rv_entry_canncel/handler.py
    environment:
      TABLE: ${self:custom.table}
      NOTIC_URL: ${env:NOTIC_URL}
    layers:
      - { Ref: UtilsLayerLambdaLayer }
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: /rv/entry/canncel
          method: get
  rv_entry_giveup:
    handler: src/lambda/rv_entry_giveup/handler.main
    package:
      include:
        - src/lambda/rv_entry_giveup/handler.py
    environment:
      TABLE: ${self:custom.table}
    layers:
      - { Ref: UtilsLayerLambdaLayer }
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: /rv/entry/giveup
          method: get
  rv_terminal_regist:
    handler: src/lambda/rv_terminal_regist/handler.main
    package:
      include:
        - src/lambda/rv_terminal_regist/handler.py
    environment:
      TABLE: ${self:custom.table}
    layers:
      - { Ref: UtilsLayerLambdaLayer }
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: /rv/terminal/regist
          method: get
  rv_history:
    handler: src/lambda/rv_history/handler.main
    package:
      include:
        - src/lambda/rv_history/handler.py
    environment:
      TABLE: ${self:custom.table}
    layers:
      - { Ref: UtilsLayerLambdaLayer }
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: /rv/match/data
          method: get
  # DataAPI
  vgws_start:
    handler: src/lambda/vgws/start/handler.main
    package:
      include:
        - src/lambda/vgws/start/handler.py
    environment:
      TABLE: ${self:custom.table}
    layers:
      - { Ref: UtilsLayerLambdaLayer }
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: /vgws/start
          method: get
  vgws_update:
    handler: src/lambda/vgws/update/handler.main
    package:
      include:
        - src/lambda/vgws/update/handler.py
    environment:
      TABLE: ${self:custom.table}
    layers:
      - { Ref: UtilsLayerLambdaLayer }
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: /vgws/update
          method: get
  vgws_finish:
    handler: src/lambda/vgws/finish/handler.main
    package:
      include:
        - src/lambda/vgws/finish/handler.py
    environment:
      TABLE: ${self:custom.table}
    layers:
      - { Ref: UtilsLayerLambdaLayer }
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: /vgws/finish
          method: get
  vgws_fetch:
    handler: src/lambda/vgws/fetch/handler.main
    package:
      include:
        - src/lambda/vgws/fetch/handler.py
    environment:
      TABLE: ${self:custom.table}
    layers:
      - { Ref: UtilsLayerLambdaLayer }
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: /vgws/fetch
          method: get
  vgws_fetch_all:
    handler: src/lambda/vgws/fetch_all/handler.main
    package:
      include:
        - src/lambda/vgws/fetch_all/handler.py
    environment:
      TABLE: ${self:custom.table}
    layers:
      - { Ref: UtilsLayerLambdaLayer }
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: /vgws/fetchall
          method: get
  ### OtherWorldConnection
  vgws_passcode_register:
    handler: src/lambda/vgws/passcode/register/handler.main
    package:
      include:
        - src/lambda/vgws/passcode/register/handler.py
    environment:
      TABLE: ${self:custom.table}
    layers:
      - { Ref: UtilsLayerLambdaLayer }
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: /vgws/passcode/regist
          method: get
  vgws_passcode_start:
    handler: src/lambda/vgws/passcode/start/handler.main
    package:
      include:
        - src/lambda/vgws/passcode/start/handler.py
    environment:
      TABLE: ${self:custom.table}
    layers:
      - { Ref: UtilsLayerLambdaLayer }
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: /vgws/passcode/start
          method: get
  vgws_passcode_answer:
    handler: src/lambda/vgws/passcode/answer/handler.main
    package:
      include:
        - src/lambda/vgws/passcode/answer/handler.py
    environment:
      TABLE: ${self:custom.table}
    layers:
      - { Ref: UtilsLayerLambdaLayer }
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: /vgws/passcode/answer
          method: get
  vgws_passcode_check:
    handler: src/lambda/vgws/passcode/check/handler.main
    package:
      include:
        - src/lambda/vgws/passcode/check/handler.py
    environment:
      TABLE: ${self:custom.table}
    layers:
      - { Ref: UtilsLayerLambdaLayer }
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: /vgws/passcode/check
          method: get
  # COUNT UP
  vgws_countup:
    handler: src/lambda/vgws/clearcount/count_up/handler.main
    package:
      include:
        - src/lambda/vgws/clearcount/count_up/handler.py
    environment:
      TABLE: ${self:custom.table}
      NAZOWA_URL: ${env:NAZOWA_URL}
      NAZPWA_ID: ${env:NAZPWA_ID}
    layers:
      - { Ref: UtilsLayerLambdaLayer }
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: /vgws/count/up
          method: get
  vgws_countup_fetch:
    handler: src/lambda/vgws/clearcount/fetch_count/handler.main
    package:
      include:
        - src/lambda/vgws/clearcount/fetch_count/handler.py
    environment:
      TABLE: ${self:custom.table}
    layers:
      - { Ref: UtilsLayerLambdaLayer }
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: /vgws/count/fetch
          method: get
resources:
  Resources:
    VRCVSTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.table}
        AttributeDefinitions:
          - AttributeName: attribute_name
            AttributeType: S
          - AttributeName: attribute_key
            AttributeType: S
        KeySchema:
          - AttributeName: attribute_name
            KeyType: HASH
          - AttributeName: attribute_key
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TimeToLiveSpecification:
          AttributeName: TTL
          Enabled: True
